[Feature] Create Applications graphql queries
uwblueprint/richmond-centre-for-disability pull request #12
Opened 2021-06-17 00:24 UTC by angeladietz

## Notion ticket link

[Set up GQL queries for Applications](https://www.notion.so/uwblueprintexecs/Set-up-GQL-queries-for-Applications-952491d4caef4a23a3d6a01f6a1215a7)

## Implementation description
* Added GraphQL queries `applications` and mutation` createApplication`
* Generated Typescript types

## Notes
* Still haven't implemented error handling for field length constraint. Will do this once PR #7 is merged.

## Checklist
- [ ] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

2021-06-17 00:26 UTC, angeladietz commented on lib/applications/resolvers.ts
> +      guardianNotes,
If anyone is nifty with typescript and can suggest an alternative to this monstrosity that would be great 🥺

2021-06-20 17:13 UTC, OustanDing requested changes

2021-06-20 17:13 UTC, OustanDing commented on lib/applications/schema.graphql
> +  aid: [Aid!]
Since `aid` is non-null in our DB, we should have: 
```suggestion
  aid: [Aid!]!
```

Same for the create mutation input.

2021-06-20 17:13 UTC, OustanDing commented on lib/applications/errors.ts
> + * Applicantion field too long error
```suggestion
 * Application field too long error
```

2021-06-20 17:13 UTC, OustanDing commented on lib/applications/resolvers.ts
> +      err.meta.target.includes('applicantId')
```suggestion
      err.meta?.target.includes('applicantId')
```

if `err.meta` can be undefined, it should be this.

2021-06-20 17:13 UTC, OustanDing commented on prisma/schema.prisma
> +  email     String   @unique @db.VarChar(255)
Don't know why `emailVerified` got deleted here. This is very likely the reason for the build failing.

2021-06-22 04:53 UTC, OustanDing reviewed
Got a small merge conflict in `package.json` - once that's resolved (keep `ts-node`) everything LGTM and is good to merge!

2021-06-22 15:48 UTC, OustanDing approved these changes
LGTM! Good work :D

2021-06-23 03:12 UTC, merged