[Feature] Created Additional Information Card
uwblueprint/richmond-centre-for-disability pull request #156
Opened 2022-03-20 17:57 UTC by aaggarwal10

## Notion ticket link

[Additional Information Card](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=fc2f1645b07f4897a7bd5b2e3e5a7a5b)

## Implementation description
* Added Card Form only for viewing (no editing)
![Card](https://user-images.githubusercontent.com/30203792/159175880-96bcfd47-b901-4f59-b402-64bd2e2595fc.png)

## Notes
* Verify display states, what different fields should be showing on diff conditions. (i.e. usesAccessibleConvertedVan = false, should additional information even be visible)

## Checklist
- [X] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

2022-03-21 20:40 UTC, OustanDing requested changes
For the ReviewInformationModal, could you please remove the `<form>` wrapping around the cards? By having the form there, when we click the button, the form gets submitted and the page refreshes. Semantically, the cards are not a form (there are no inputs). Rather, remove the `type="submit"` from the button and just add `onClick={onConfirmed}` to the button.

2022-03-21 20:40 UTC, OustanDing commented on components/admin/requests/processing/ReviewInformationModal.tsx
> +                  </>
For new requests, there will also be a guardian/POA card and a physician assessment card. We will need to add an extra condition block here to account for those sections. We don't have a PhysicianAssessment card yet, but let's add the guardian card for now.

2022-03-21 20:40 UTC, OustanDing commented on components/admin/requests/additional-questions/Card.tsx
> +                    : 'Not Given'}
```suggestion
                  {requiresWiderParkingSpaceReason
                    || otherRequiresWiderParkingSpaceReason
                    || 'Not Given'}
```

2022-03-21 20:40 UTC, OustanDing commented on components/admin/requests/additional-questions/Card.tsx
> +                    : 'Not Given'}
Actually, the above code is not the exact code we should use. If `requiresWiderParkingSpaceReason` is non-null, we should convert the enum to a string, similar to lines 75-77 (loading method)

2022-03-23 00:12 UTC, OustanDing requested changes

2022-03-23 00:12 UTC, OustanDing commented on components/admin/requests/processing/review-information.ts
> +    }
We don't want to query the guardian via the applicant, as that is already on record. We want to pull the guardian information filled out in the application itself. Instead, we want to query the following:
```suggestion
    application(id: $id) {
      __typename
      id
      type
      ... on NewApplication {
        guardianFirstName
        guardianMiddleName
        guardianLastName
        etc...
      }
    }
```
which uses [GraphQL fragments](https://graphql.org/learn/queries/#fragments) to only query the guardian fields when we are dealing with a new application

2022-03-23 00:12 UTC, OustanDing commented on components/admin/requests/processing/review-information.ts
> +  };
Types here need to be updated when above change is implemented.

2022-03-24 07:23 UTC, OustanDing approved these changes
Key changes made:
- Move GQL query from Review Modal level to Guardian Info card level (consistent with other cards, easier to reuse)
- Add `isSubsection` prop to cards when they are subsections of other cards - setting to `true` will make the border dashed (see designs)
- Small fix to GQL schema, fixed guardian fields being non-null when querying for new application

2022-03-24 12:29 UTC, merged

2022-03-24 17:56 UTC, carelynntsai commented
Hello! Just wanted to confirm that an "Address" subhead got added to the review doctor's information section since it wasn't in the old screenshot 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/38408276/159979206-39b6b1c7-fedf-498f-aee7-4467dda4418b.png">

Also the below scenario shouldn't ever actually happen, this was just some test placeholder data right?
<img width="679" alt="image" src="https://user-images.githubusercontent.com/38408276/159980139-6269acdd-f187-487b-bae3-cafc16393ee4.png">

2022-03-24 23:48 UTC, aaggarwal10 commented
First Design Comment Fixed in PR #156 
Second Design Comment Is from Old Process, No Longer Occurs with new logic