[Feature] Added Completion Footer for Processing Tasks
uwblueprint/richmond-centre-for-disability pull request #164
Opened 2022-03-30 00:21 UTC by aaggarwal10

## Notion ticket link

[Add Footer for completing request](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=52eb3c79cb4d4097bc08bf701afc965c)

## Implementation description
* Added Footer using `Chakra UI` with `Complete request` button and `View permit holder`
* Removed old complete request button
* Hooked up View permit holder with custom GraphQL query

## Checklist
- [X] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

2022-03-31 18:41 UTC, chrischan325 approved these changes
Everything looks good to me, assuming the backend processes of completing request is not included in this ticket

2022-03-31 21:02 UTC, OustanDing requested changes

2022-03-31 21:02 UTC, OustanDing commented on tools/admin/requests/view-request.ts
> +
This query is not necessary. One of the main benefits of GraphQL is that you can query for whatever you need in just one query. Thus, you can select `applicant > id` from the application in the `GET_APPLICATION_QUERY` above.

2022-03-31 21:02 UTC, OustanDing commented on pages/admin/request/[id].tsx
> +  const [permitHolderID, setPermitHolderID] = useState<number | undefined>(undefined);
This state variable isn't needed. After querying for the applicant ID in the existing GQL query in this file, just destructure it from `data`

2022-03-31 21:03 UTC, OustanDing commented
Also, good idea to use `Portal` to build the footer! We should use that across our app in general

2022-03-31 21:15 UTC, OustanDing commented on components/admin/requests/Header.tsx
> +          <Portal>
Can we extract this to a component named `ProcessingFooter` and put it in `components/admin/requests`?

2022-04-01 03:13 UTC, OustanDing commented on components/admin/Footer.tsx
> +export default function ProcessingTasksFooter({ children }: ProcessingTasksFooterProps) {
```suggestion
export default function Footer({ children }: ProcessingTasksFooterProps) {
```
We will use this component as a generic footer wrapper

2022-04-01 03:13 UTC, OustanDing commented on components/admin/requests/Header.tsx
> +  applicantId: permitHolderId,
```suggestion
  applicantId,
```

2022-04-01 03:13 UTC, OustanDing commented on components/admin/requests/Header.tsx
> +            permitHolderId={permitHolderId}
```suggestion
            permitHolderId={applicantId}
```

2022-04-01 03:13 UTC, OustanDing commented on components/admin/requests/processing/ProcessingFooter.tsx
> +  readonly permitHolderId?: number;
```suggestion
  readonly applicantId?: number;
```

2022-04-01 03:13 UTC, OustanDing commented on components/admin/requests/processing/ProcessingFooter.tsx
> +  permitHolderId,
```suggestion
  applicantId,
```

2022-04-01 03:13 UTC, OustanDing commented on components/admin/requests/processing/ProcessingFooter.tsx
> +            </Link>
```suggestion
                <CompleteRequestModalButton
                  applicationId={applicationId}
                  isDisabled={!allStepsCompleted}
                />
```
This should not be wrapped in `Link` as it does not navigate to a new page route

2022-04-01 03:13 UTC, OustanDing commented on pages/admin/request/[id].tsx
> +  const permitHolderID = data.application.applicant?.id;
```suggestion
  const applicantId = data.application.applicant?.id;
```

2022-04-01 22:26 UTC, OustanDing approved these changes
LGTM!

Design approved by Vedant as well.

2022-04-02 18:45 UTC, merged