[Improvement] Added Loading State Spinners to Request & Permit Holder Tables
uwblueprint/richmond-centre-for-disability pull request #189
Opened 2022-05-06 01:44 UTC by aaggarwal10

## Notion ticket link

[Add Loading States for Request & Permit Holder Tables](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=4c73535599df45d6baaad79829933e80)

## Implementation description
* Added Loading Component to Table
* Called Loading component with loading parameter from `useQuery`

## [Design Video](https://www.loom.com/share/71562fb0364c476b9ec48b6805c5c6fd)

## Checklist
- [X] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

2022-05-06 02:05 UTC, OustanDing requested changes

2022-05-06 02:05 UTC, OustanDing commented on components/Table.tsx
> +      {!loading && (
Please replace this with a ternary operator

2022-05-08 17:54 UTC, vedantdsn approved these changes

2022-05-11 01:30 UTC, OustanDing approved these changes

2022-05-11 02:08 UTC, merged