Add Loading States to Processing Task Card
uwblueprint/richmond-centre-for-disability pull request #193
Opened 2022-05-10 02:18 UTC by chrischan325

## Notion ticket link

[Loading states for processing tasks card](https://www.notion.so/uwblueprintexecs/Loading-states-for-processing-tasks-card-10c896afd09e478ebb77b2af5c4ab77d)

## Implementation description
* Added loading states to mark as complete buttons as well as undo buttons

## Notes
* 

## Checklist
- [x] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

2022-05-11 01:26 UTC, OustanDing approved these changes
LGTM for dev! Still awaiting design approval

2022-05-11 01:26 UTC, OustanDing commented on components/admin/requests/processing/TasksCard.tsx
> +                  isLoading={assignAppNumberLoading}
Need `isDisabled` prop here, same for below

2022-05-11 01:27 UTC, OustanDing requested changes
One change requested, please see previous comment

2022-05-12 01:36 UTC, OustanDing approved these changes
LGTM!

2022-05-12 21:24 UTC, carelynntsai approved these changes
🤩 mvp

2022-05-13 00:33 UTC, merged