[Improvement] Empty State Components Added to Request & Permit Holder Tables
uwblueprint/richmond-centre-for-disability pull request #195
Opened 2022-05-10 21:44 UTC by aaggarwal10

## Notion ticket link

[Add empty states for Request & Permit Holder Tables](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=9d22a3cb787e44e0ac68d5888881f9d4)

## Implementation description
* Added Empty States to Permit Holder & Request Pages
* Permit Holder Page:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/30203792/167726756-149434ea-f3b1-4bb7-bc3c-0777f8b6c8b5.png">
* Request Page:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/30203792/167726836-3a7bf630-2aab-40da-9c73-0ad24f294d87.png">

## Notes
* Extracted Component from `reports.tsx` adding a custom component in `components/admin` to be used in Request, Permit Holder, and Reports Page. 

## Checklist
- [X] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

2022-05-11 01:38 UTC, OustanDing requested changes

2022-05-11 01:38 UTC, OustanDing commented on components/admin/EmptyStateComponent.tsx
> +import { Box, Text } from '@chakra-ui/react'; // Chakra UI
Please move and rename this file to `components/EmptyMessage.tsx`

2022-05-11 01:38 UTC, OustanDing commented on components/admin/EmptyStateComponent.tsx
> +  readonly subMessage: string;
```suggestion
  readonly title: string;
  readonly message: string;
```

2022-05-11 01:38 UTC, OustanDing commented on components/admin/EmptyStateComponent.tsx
> +      <Text padding="12px 0 12px" textStyle="display-large">
```suggestion
      <Text padding="12px 0" textStyle="display-large">
```

2022-05-11 09:37 UTC, carelynntsai commented
I can't formally approve this because of the merge conflicts but it looks good from my end

2022-05-12 02:01 UTC, OustanDing requested changes

2022-05-12 02:01 UTC, OustanDing commented on pages/admin/index.tsx
> +import EmptyStateComponent from '@components/EmptyMessage';
Could you please change all imported names for this component to `EmptyMessage` now?

2022-05-12 03:51 UTC, OustanDing approved these changes
LGTM!

2022-05-13 03:02 UTC, merged