[WIP] Personal Information Form Backend Validation
uwblueprint/richmond-centre-for-disability pull request #207
Opened 2022-05-29 17:29 UTC by j-bunk

## Notion ticket link

[Personal Information Form Backend Validation](https://www.notion.so/uwblueprintexecs/Personal-Information-Form-Backend-Validation-f5f911bd3d5e4657b34fb8227e12740e)

## Implementation description

Remaining TODOs:
- [ ] Resolve bug with backend validation for new applications
- [ ] Test more thoroughly

## Notes
* 

## Checklist
- [ ] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

2022-06-03 01:26 UTC, OustanDing requested changes

2022-06-03 01:26 UTC, OustanDing commented on tools/admin/requests/permit-holder-information.ts
> +export type UpdateNewPermitHolderInformationResponse = {
```suggestion
export type UpdateNewApplicationPermitHolderInformationResponse = {
```

2022-06-03 01:26 UTC, OustanDing commented on lib/applicants/resolvers.ts
> +    throw Error;
Remove

2022-06-03 01:26 UTC, OustanDing commented on lib/applicants/validation.ts
> +    id: number().positive('Application not found').required('Application not found'),
Fix error messages based on previous comment

2022-06-04 21:12 UTC, j-bunk commented on tools/admin/requests/permit-holder-information.ts
> +export type UpdateNewPermitHolderInformationResponse = {
Addressed!

2022-06-04 21:12 UTC, j-bunk commented on lib/applicants/resolvers.ts
> +    throw Error;
Addressed!

2022-06-04 21:12 UTC, j-bunk commented on lib/applicants/validation.ts
> +    id: number().positive('Application not found').required('Application not found'),
Addressed!

2022-06-04 21:19 UTC, j-bunk commented
@OustanDing Unrelated to my changes but I noticed you can select `Other` as a gender but there isn't a way to specify what that gender is

2022-06-05 03:14 UTC, OustanDing commented
@j-bunk Thanks for bringing that up, noted

2022-06-05 03:18 UTC, OustanDing approved these changes

2022-06-05 03:58 UTC, merged