[Validation] Add 6 month restricted window for applicant renewal
uwblueprint/richmond-centre-for-disability pull request #209
Opened 2022-06-01 23:20 UTC by chrischan325

## Notion ticket link

[Add 6 month restricted window for renewal after permit expiry date to applicant renewal flow](https://www.notion.so/uwblueprintexecs/Add-6-month-restricted-window-for-renewal-after-permit-expiry-date-to-applicant-renewal-flow-57af9b1ba0784a02aa4d076d635171ad)

## Implementation description
* 

## Notes
* 

## Checklist
- [ ] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

2022-06-01 23:58 UTC, aaggarwal10 requested changes

2022-06-01 23:58 UTC, aaggarwal10 commented on lib/applicants/resolvers.ts
> +  if (moment(mostRecentPermit.expiryDate).add(6, 'M') >= moment()) {
`momentRecentPermit.expiryDate` is inputed as a UTC Datetime object. (i.e. YYYY-MM-DD) so this code will convert it to our local time zone which we do not want I believe. I think the proper code should be `moment.utc(mostRecentPermit.expiryDate).add(6, 'M') >= mpment())` but this needs to be verified via testing.

2022-06-02 01:01 UTC, OustanDing requested changes

2022-06-02 01:01 UTC, OustanDing commented on lib/applicants/resolvers.ts
> +  // Note: 30 days = 30 * 24 * 60 * 60 * 1000 milliseconds
Remove this comment (confusing)

2022-06-02 01:01 UTC, OustanDing commented on lib/applicants/resolvers.ts
> +  if (moment.utc(mostRecentPermit.expiryDate).add(6, 'M') >= moment()) {
```suggestion
  if (moment.utc(mostRecentPermit.expiryDate).add(6, 'M') < moment()) {
```

2022-06-02 01:18 UTC, aaggarwal10 approved these changes

2022-06-08 03:09 UTC, merged