[Feature] Set up Next Auth authentication
uwblueprint/richmond-centre-for-disability pull request #6
Opened 2021-06-12 02:56 UTC by OustanDing

_WIP_

- Set up Next Auth with email provider
- Create `sendVerificationRequest` function for sending email to users
- Update DB and Prisma schema to store verification requests and email verifications

TODO:
- Create basic login page for testing
- Disallow registration (only allow login for accounts that exist in the DB)

2021-06-13 05:42 UTC, jeffreyzhang2001 requested changes
LGTM from some local testing (other than some small comments). Would be nice to have a logout button as well before merging it in. Good work :)

2021-06-13 05:42 UTC, jeffreyzhang2001 commented on pages/api/auth/[...nextauth].ts
> +      maxAge: 24 * 60, // 1 hour max life for login request
Should be 60 * 60 (1 hour)

2021-06-13 05:42 UTC, jeffreyzhang2001 commented on pages/api/auth/[...nextauth].ts
> +      if (!user || !user.email) {
I think we can just do !user?.email here.

2021-06-14 02:57 UTC, OustanDing commented on pages/api/auth/[...nextauth].ts
> +      maxAge: 24 * 60, // 1 hour max life for login request
Good catch

2021-06-14 03:12 UTC, jeffreyzhang2001 commented
LGTM!

2021-06-14 03:12 UTC, jeffreyzhang2001 approved these changes

2021-06-14 03:22 UTC, merged