[Feature] Chakra UI theme setup
uwblueprint/richmond-centre-for-disability pull request #9
Opened 2021-06-16 01:51 UTC by OustanDing

## Notion ticket link

[Ticket](https://www.notion.so/uwblueprintexecs/Configure-Chakra-UI-theme-b517ab3f4c9b4b559fc530254689fe28)

## Implementation description
* Configured theme typography, colours, shadows, spacing
* Configured default text styles
* Overrode default component styles and tested custom styles
* Installed fonts
* Small changes to existing frontend

## Checklist
- [ ] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

2021-06-16 03:20 UTC, jeffreyzhang2001 requested changes

2021-06-16 03:20 UTC, jeffreyzhang2001 commented on pages/login.tsx
> +        <Button onClick={signInWithEmail}>Log in</Button>
Can we refactor this slightly? I think we can wrap the entire thing up in a form like this, without having to write an onKeyUp fn to support enter key submit.

```
<form>
  <FormControl>
        ....
  </FormControl>
  <Button onClick={() => signInWithEmail}>Log in</Button>
</form>
```

2021-06-16 03:21 UTC, jeffreyzhang2001 commented
Just one small nit. Otherwise, LGTM

2021-06-16 23:28 UTC, jeffreyzhang2001 approved these changes

2021-06-17 00:54 UTC, OustanDing reviewed
@jeffreyzhang2001 Changes look great. Just one small suggestion then we can ship it

2021-06-17 00:54 UTC, OustanDing commented on pages/login.tsx
> +            <Input
Could we also disable the Input field while it's signing in?

2021-06-17 01:20 UTC, merged